# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    # mac:
    #   imageName: "macos-10.14"
    windows:
      imageName: "vs2017-win2016"

pool:
  vmImage: $(imageName)

steps:
# Linux
- bash: |
    docker build -t riot .
    docker run --rm -v $(Build.ArtifactStagingDirectory):/data riot linux
  condition: eq( variables['Agent.OS'], 'Linux' )
  displayName: Build Riot desktop for linux in a docker container

# Windows
- bash: |
    echo $(Build.ArtifactStagingDirectory)
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: Test windows

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/dist/'
    artifactName: Linux_Build
  condition: eq( variables['Agent.OS'], 'Linux' )
